galaxy_info:
  author: jittakal
  description: Docker Engine Installation
  company: jittakal
  license: license (Apache)
  min_ansible_version: 2.1
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  galaxy_tags: []
dependencies: []